; PlatformIO configuration for Wall-A Arduino firmware
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit Motor Shield library@^1.0.1
